### ISSUE TITLE
Numbers of properties from wikidata don't match with local instance

### ISSUE THREAD

**Issue by MHuberFaust** [UB-Mannheim/RaiseWikibase#12]
Hi there,

I'm trying to use the wikidata model for my local instance. After using miniWikibase.py properties in my local instance don't match the ones in wikidata (e.g. property "images" is P10 local, P18 at Wikidata.

Does it work as intended? If yes, is there a way to keep Wikidata's numbering?

**Comment by renat-kaufmann** [comment]
Hi Michael,
1. Yes, it works as intended. Every local property has also a statement with Wikidata ID.
2. Currently no. There could be an ugly workaround, but I would rather wait for Wikibase 1.36 with fully federated properties (expected at the end of 2021).

**Comment by MHuberFaust** [comment]
Thx a lot!
