### ISSUE TITLE
docker.py uses wrong container name

### ISSUE THREAD

**Issue by MHuberFaust** [UB-Mannheim/RaiseWikibase#13]
Hi,
I freshly installed RaiseWikibase and could not use the scripts properly. After a while I found the problem:

Container names have hyphens in their name. 

docker_names() in docker.py uses underscores instead if hyphens:

`if names:
        names = [s.decode('ascii').replace('\n', '') for s in names]
        mysql = [k for k in names if '_mysql_' in k][0]
        wikibase = [k for k in names if '_wikibase_' in k][0]`

adjusting the code to
`if names:
        names = [s.decode('ascii').replace('\n', '') for s in names]
        mysql = [k for k in names if '-mysql-' in k][0]
        wikibase = [k for k in names if '-wikibase-' in k][0]`

solved the issue.

It might be useful adjust the command from this issue as well: #4 

Best,
Michael

**Comment by renat-kaufmann** [comment]
Hi Michael, thank you for reporting this. I did test it with hyphens in Debian, it worked. Are you running it on Windows?

**Comment by MHuberFaust** [comment]
I run it on Mac.

**Comment by MHuberFaust** [comment]
So this is weird: I cleared the data from my wikibase instance (as mentioned in youre Readme) and the container names went back to "normal" (names with underscores).
Do you have any ideas?

<img width="1174" alt="Screenshot 2021-11-11 at 07 45 38" src="https://user-images.githubusercontent.com/2339760/141251511-612723c8-e0ad-4024-9371-804c3b794372.png">

 I can work around that, no big deal, just seems strange :)

**Comment by renat-kaufmann** [comment]
Yeah, that's strange. No idea what's that. Since now it works as expected, I am closing the issue. Please reopen if it will repeat.

**Comment by MHuberFaust** [comment]
It happened again after a docker desktop update. Switching back to docker compose v1 did it for me.

[here](https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore/69895110) is a good explanation.
Since the latest versions of docker compose moved away from underscores it might be useful to adjust the code to fit both versions.

**Comment by renat-kaufmann** [comment]
I see, thank you! I'll fix it now.
