### ISSUE TITLE
Windows installation (2)

### ISSUE THREAD

**Issue by MHuberFaust** [UB-Mannheim/RaiseWikibase#19]
Hi again,

I started installing RaiseWikibase on a Mac parallel to Windows, so I can see if problems are Windows specific.

The jobrunner seems to have, again, an issue with (probably) encoding:
```

")syntax error: invalid arithmetic operator (error token is "

")syntax error: invalid arithmetic operator (error token is "

wait-for-it.sh: waiting for mysql.svc:3306 without a timeout

wait-for-it.sh: mysql.svc:3306 is available after 0 seconds

/jobrunner-entrypoint.sh: line 12: $'\r': command not found

/jobrunner-entrypoint.sh: line 13: syntax error near unexpected token `$'{\r''

'jobrunner-entrypoint.sh: line 13: `kill_runner() {

/jobrunner-entrypoint.sh: line 2: $'\r': command not found

/jobrunner-entrypoint.sh: line 5: $'\r': command not found

")syntax error: invalid arithmetic operator (error token is "

")syntax error: invalid arithmetic operator (error token is "

wait-for-it.sh: waiting for mysql.svc:3306 without a timeout

wait-for-it.sh: mysql.svc:3306 is available after 0 seconds

sleep: invalid time interval '1\r'

Try 'sleep --help' for more information.
```

Line endings are differently encoded. Is there a way to ensure they have the correct one for Windows as well?

Best,
Michael

**Comment by renat-kaufmann** [comment]
Hi Michael, the [jobrunner-entrypoint.sh](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/jobrunner-entrypoint.sh) comes from [Wikibase Release Pipeline](https://github.com/wmde/wikibase-release-pipeline). May be you could report it there or even at Phabricator.

Do you run `docker-compose -f docker-compose.yml -f docker-compose.extra.yml up -d --scale wikibase_jobrunner=2` ? What does it say if you run only `docker-compose -f docker-compose.yml -f docker-compose.extra.yml up -d` ?

**Comment by MHuberFaust** [comment]
Well that one is on me :(

I must have opened the file with a Texteditor and Windows converted linebreaks etc... and could not reproduce the issue.

I need to install the whole package on a different windows machine in a few days. I will reopen the issue if it shows again.
