### ISSUE TITLE
German time zone and time offset

### ISSUE THREAD

**Issue by shigapov** [UB-Mannheim/RaiseWikibase#2]
Setting time zone and time offset in Wikibase is described at [Manual:Timezone](https://www.mediawiki.org/wiki/Manual:Timezone). In our case with the German time zone setting those variables does not change the time zone in `docker-compose logs -f`.

**Comment by dmcmilla** [comment]
I modified  the timenow variable defined in the insert method in dbconnection.py to call utcnow() instead of now() since we are storing everything based off of UTC.  I'm not sure if this addresses this specific issue or not.

**Comment by renat-kaufmann** [comment]
Those logs are coming from Wikibase Docker even before any edits by RaiseWikibase... But it's a good idea to use utcnow() instead of now(). Would you like to make a pull request on that?

**Comment by renat-kaufmann** [comment]
now() is replaced by utcnow() in [commit](https://github.com/UB-Mannheim/RaiseWikibase/commit/2c7e9adfffa1f285e946b6b65b593ac913dae1f7)
