### ISSUE TITLE
Installation issue with mysql-client

### ISSUE THREAD

**Issue by MHuberFaust** [UB-Mannheim/RaiseWikibase#6]
Hi,
running the setup on a macOS ran into a problem with pip and mysql-client.

> Collecting mysqlclient>=2.0.3
  Downloading mysqlclient-2.0.3.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 6.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s1/wc7ltyyd3f73b2gh8gshnvtc0000gn/T/pip-install-o_0z3drp/mysqlclient_1f5cda9615b8453bad17f80955388a33/setup.py'"'"'; __file__='"'"'/private/var/folders/s1/wc7ltyyd3f73b2gh8gshnvtc0000gn/T/pip-install-o_0z3drp/mysqlclient_1f5cda9615b8453bad17f80955388a33/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s1/wc7ltyyd3f73b2gh8gshnvtc0000gn/T/pip-pip-egg-info-0filxfa_
         cwd: /private/var/folders/s1/wc7ltyyd3f73b2gh8gshnvtc0000gn/T/pip-install-o_0z3drp/mysqlclient_1f5cda9615b8453bad17f80955388a33/
    Complete output (15 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s1/wc7ltyyd3f73b2gh8gshnvtc0000gn/T/pip-install-o_0z3drp/mysqlclient_1f5cda9615b8453bad17f80955388a33/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/private/var/folders/s1/wc7ltyyd3f73b2gh8gshnvtc0000gn/T/pip-install-o_0z3drp/mysqlclient_1f5cda9615b8453bad17f80955388a33/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/s1/wc7ltyyd3f73b2gh8gshnvtc0000gn/T/pip-install-o_0z3drp/mysqlclient_1f5cda9615b8453bad17f80955388a33/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    mysql_config --version
    mariadb_config --version
    mysql_config --libs
    ----------------------------------------

I solved it by following the steps listed :[here](https://pypi.org/project/mysqlclient/)

Thank you for creating this library :)

**Comment by renat-kaufmann** [comment]
Thank you for reporting it! Can be helpful for others.
